### ISSUE TITLE
AttributeError: Can't pickle local object 'augment_visit.<locals>.augment_func'

### ISSUE THREAD

**Issue by dineshtrivedi** [PyCQA/pylint-plugin-utils#20]
According to https://github.com/PyCQA/pylint-django/issues/276 we need to change the code so the PyLinter remains pickleable after the usage of `augment_visit` and `suppress_message`

**Comment by carlio** [comment]
@dineshtrivedi I have merged in the PR #21 and released version `0.7` to PyPI. 
I got the pylint-django tests running with it too so it's looking good :-)
